### ISSUE TITLE
publish separate modules for OWL API 4 & 5

### ISSUE THREAD

**Issue by balhoff** [phenoscape/scowl#129]
See https://github.com/phenoscape/scowl/pull/127#issuecomment-1061991063

**Comment by balhoff** [comment]
@francesco-kriegel I published `scowl-owlapi5` to Maven Central. Would you mind trying it out? (It may take a little while to appear there).

**Comment by francesco-kriegel** [comment]
In my prototype it works flawlessly with the version from Maven Central.  Thank you for the new separate module supporting OWLAPI 5.

**Comment by balhoff** [comment]
Great, thanks for checking.
