### ISSUE TITLE
What's a GCI?

### ISSUE THREAD

**Issue by LeifW** [phenoscape/scowl#38]
The README mentions: [Add some axioms and programmatically generated GCIs to an ontology](https://github.com/phenoscape/scowl#add-some-axioms-and-programmatically-generated-gcis-to-an-ontology), but I don't know what a GCI is and Google has not been helpful in clarifying that.

**Comment by LeifW** [comment]
"General Concept Inclusions"? http://ontogenesis.knowledgeblog.org/1288

**Comment by balhoff** [comment]
Yes, exactly. The docs aren't worded very well, as GCIs are axioms themselves.
